import customtkinter as tk
def menos():
    n1 = float(input1.get())
    n2 = float(input2.get())
    texto1.configure(text=f'{n1-n2}')
def mais():
    n1 = float(input1.get())
    n2 = float(input2.get())
    texto1.configure(text=f'{n1+n2}')
def mults():
    n1 = float(input1.get())
    n2 = float(input2.get())
    texto1.configure(text=f'{n1*n2}')
def divs():
    n1 = float(input1.get())
    n2 = float(input2.get())
    texto1.configure(text=f'{n1/n2}')
tk.set_appearance_mode('Dark')
janela = tk.CTk()
janela.title('Calculadora')
janela.geometry('500x500')
janela.configure(fg_color='#333339')
janela.resizable(width=False, height=False)
colunas = list(range(13))
linhas = list(range(13))
janela.grid_columnconfigure(colunas,weight=1)
janela.grid_rowconfigure(linhas,weight=1)
texto1 = tk.CTkLabel(janela, text='calcular notas', font=("Quicksand"'bold',16),text_color='white')
input1 = tk.CTkEntry(janela,placeholder_text='Número 1', text_color='white',width=200, height=35, fg_color='transparent',placeholder_text_color='white',border_color='#f5365f')
input2 = tk.CTkEntry(janela,placeholder_text='Número 2', text_color='white',width=200, height=35, fg_color='transparent',placeholder_text_color='white',border_color='#f5365f')
sub = tk.CTkButton(janela, text='-',font=("Quicksand"'bold',16),fg_color='#f5365f',hover_color='#b52645',text_color='white', width=100, height=35, command= menos)
soma = tk.CTkButton(janela, text='+',font=("Quicksand"'bold',16),fg_color='#f5365f',hover_color='#b52645',text_color='white', width=100, height=35, command= mais)
mult = tk.CTkButton(janela, text='x',font=("Quicksand"'bold',16),fg_color='#f5365f',hover_color='#b52645',text_color='white', width=100, height=35, command= mults)
div = tk.CTkButton(janela, text='÷',font=("Quicksand"'bold',16),fg_color='#f5365f',hover_color='#b52645',text_color='white', width=100, height=35, command= divs)
input1.grid(row=6,column=6)
input2.grid(row=6,column=7)
sub.grid(row=7,column=6,columnspan=2)
soma.grid(row=7,column=6,)
mult.grid(row=7,column=7)
div.grid(row=8,column=6,columnspan=2,rowspan=1)
texto1.grid(row=5,column=6,columnspan=2)
janela.mainloop()